require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../../../ios/native.rb'

require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '15.0'
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym

  # Force statically-linked pods to stay static under dynamic frameworks.
  # - GoogleMaps ships static .xcframeworks that conflict with dynamic linkage.
  # - RNReanimated fails to resolve React (RCTEventDispatcher) and Hermes
  #   inspector symbols (enableDebugging/disableDebugging) across the dynamic-
  #   framework boundary; static-linking it pulls those symbols in directly.
  #   Reanimated + use_frameworks! + Hermes has no official fix (see
  #   software-mansion/react-native-reanimated#3768).
  if linkage.to_sym == :dynamic
    force_static = [
      'GoogleMaps', 'GoogleMapsBase', 'GoogleMapsCore',
      'Google-Maps-iOS-Utils', 'react-native-google-maps',
      'RNReanimated',
    ]
    pre_install do |installer|
      installer.pod_targets.each do |pod|
        if force_static.include?(pod.name)
          def pod.build_type
            Pod::BuildType.static_library
          end
        end
      end
    end
  end
end

target 'LuciqExample' do
  config = use_native_modules!
  rn_maps_path = '../node_modules/react-native-maps'
  pod 'react-native-google-maps', :path => rn_maps_path
  # XCFramework from local extracted folder
  # add this line
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # Hermes is now enabled by default. Disable by setting this flag to false.
    # Upcoming versions of React Native may rely on get_default_flags(), but
    # we make it explicit here to aid in the React Native upgrade process.
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'LuciqTests' do
    inherit! :complete
    pod 'OCMock'
    end

  post_install do |installer|
    react_native_post_install(
      installer,
      # Set `mac_catalyst_enabled` to `true` in order to apply patches
      # necessary for Mac Catalyst builds
      :mac_catalyst_enabled => false
    )
  end
end
